variable "instance_ami" {}
variable "instance_type" {}
variable "instance_name_1" {}
variable "instance_name_2" {}
variable "subnet_id" {}
variable "vpc_security_group_ids" {}
variable "key_name" {}
variable "filename" {}
variable "volume_size" {}
variable "volume_type" {}
variable "bucket_name" {}