variable "private_subnets" {}
variable "fargate_namespace_1" {}
variable "fargate_namespace_2" {}
variable "fargate_namespace_3" {}
variable "fargate_namespace_4" {}
variable "fargate_namespace_5" {}
variable "aws_eks_cluster_version" {}
variable "cidr" {}
variable "project_name" {}
variable "PROJECT_CUSTOMER" {}
variable "PROJECT_ENV" {}