variable "subnet_ids" {}
variable "number_of_broker_nodes" {}
variable "instance_type" {}
variable "volume_size" {}
variable "project_name" {}
variable "PROJECT_CUSTOMER" {}
variable "PROJECT_ENV" {}
variable "cidr" {}
variable "vpc_id" {}