variable "redis_sg" {}
variable "redis_name" {}
variable "redis_engine_version" {}
variable "redis_node" {}
variable "redis_num_shards" {}
variable "redis_num_replicas_per_shard" {}
variable "eks_sg" {}
variable "redis_snapshot_retention_limit" {}
variable "subnet_ids" {}
