variable "redis_engine_version" {}
variable "redis_node" {}
variable "redis_num_shards" {}
variable "redis_num_replicas_per_shard" {}
variable "security_group_id" {}
variable "redis_snapshot_retention_limit" {}
variable "subnet_ids" {}
variable "project_name" {}
variable "PROJECT_CUSTOMER" {}
variable "PROJECT_ENV" {}